title: Pergament
author: pro-panda
subtitle: The life of a frustrated engineer

url: "https://petarmt.github.io"
baseurl: "/parchment"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "O meni"
   link: "about"
 - name: "Resume"
   absolute-link: "https://rahulbothra.com/cv.pdf"
